"use client";

import { useState } from "react";

const contentTypes = [
  { id: "blog", name: "Blog Post", description: "Long-form article content" },
  { id: "social", name: "Social Media", description: "Captions and posts" },
  { id: "email", name: "Email", description: "Marketing or transactional" },
  { id: "product", name: "Product Description", description: "E-commerce copy" },
  { id: "creative", name: "Creative Writing", description: "Stories and narratives" },
];

const tones = ["Professional", "Casual", "Friendly", "Authoritative", "Playful", "Persuasive"];

export default function GeneratePage() {
  const [contentType, setContentType] = useState("blog");
  const [prompt, setPrompt] = useState("");
  const [tone, setTone] = useState("Professional");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState("");

  const handleGenerate = () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setGeneratedContent("");

    const selectedType = contentTypes.find((t) => t.id === contentType);
    const sampleOutput = `# ${prompt}\n\nHere is your AI-generated ${selectedType?.name.toLowerCase()} content with a ${tone.toLowerCase()} tone:\n\n## Introduction\n\nIn today's rapidly evolving digital landscape, ${prompt.toLowerCase()} has become an increasingly important topic. This article explores the key aspects and provides actionable insights for readers.\n\n## Key Points\n\n1. **Understanding the fundamentals** — Before diving deep, it's essential to grasp the core concepts that underpin this subject.\n\n2. **Current trends and developments** — The landscape is constantly shifting, and staying informed about the latest developments is crucial.\n\n3. **Practical applications** — Theory is valuable, but knowing how to apply these concepts in real-world scenarios is what sets apart true expertise.\n\n## Conclusion\n\nAs we've explored throughout this piece, ${prompt.toLowerCase()} represents both a challenge and an opportunity. By staying informed and adaptable, you can position yourself for success in this dynamic field.\n\n---\n*Generated by AI Creator Hub • ${new Date().toLocaleDateString()}*`;

    let index = 0;
    const interval = setInterval(() => {
      if (index < sampleOutput.length) {
        setGeneratedContent(sampleOutput.slice(0, index + 5));
        index += 5;
      } else {
        clearInterval(interval);
        setIsGenerating(false);
      }
    }, 10);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Generate Content</h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
          Use AI to create high-quality content in seconds.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Input Panel */}
        <div className="space-y-6 rounded-xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Content Type</label>
            <div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-2">
              {contentTypes.map((type) => (
                <button
                  key={type.id}
                  onClick={() => setContentType(type.id)}
                  className={`rounded-lg border p-3 text-left transition-colors ${
                    contentType === type.id
                      ? "border-indigo-500 bg-indigo-50 dark:border-indigo-400 dark:bg-indigo-950"
                      : "border-gray-200 hover:border-gray-300 dark:border-gray-700 dark:hover:border-gray-600"
                  }`}
                >
                  <p className={`text-sm font-medium ${
                    contentType === type.id ? "text-indigo-700 dark:text-indigo-300" : "text-gray-900 dark:text-white"
                  }`}>{type.name}</p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">{type.description}</p>
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Tone</label>
            <div className="mt-2 flex flex-wrap gap-2">
              {tones.map((t) => (
                <button
                  key={t}
                  onClick={() => setTone(t)}
                  className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
                    tone === t
                      ? "bg-indigo-600 text-white"
                      : "bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700"
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Prompt</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Describe what you want to generate..."
              rows={5}
              className="mt-2 w-full rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 placeholder-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 dark:border-gray-700 dark:bg-gray-800 dark:text-white dark:placeholder-gray-500"
            />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating || !prompt.trim()}
            className="w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-medium text-white hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-50 transition-colors"
          >
            {isGenerating ? (
              <span className="flex items-center justify-center gap-2">
                <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
                Generating...
              </span>
            ) : (
              "Generate Content"
            )}
          </button>
        </div>

        {/* Output Panel */}
        <div className="rounded-xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
          <div className="flex items-center justify-between border-b border-gray-200 px-6 py-4 dark:border-gray-800">
            <h2 className="text-sm font-medium text-gray-900 dark:text-white">Output</h2>
            {generatedContent && (
              <button
                onClick={() => navigator.clipboard.writeText(generatedContent)}
                className="rounded-md px-2.5 py-1.5 text-xs font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-800"
              >
                Copy
              </button>
            )}
          </div>
          <div className="p-6">
            {generatedContent ? (
              <div className="prose prose-sm max-w-none dark:prose-invert whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300">
                {generatedContent}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <svg className="h-12 w-12 text-gray-300 dark:text-gray-600" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                </svg>
                <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
                  Your generated content will appear here
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
